=== Garnasha/quantomatic/gui/src/com/sun/jaf/ui/resources/action-set.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
   The action_attributes parameter entity is a convenient representation
   of the common attributes between an action and an action-list.

   idref - a reference to a previously defined action. 
           
   type - if the value is "single" then the action represents a command
          action. If the value is "toggle" then the action is a multi-state
          action which may be selected or unselected. This value is
          "single" by default.
    
   name - the label for the action.

   mnemonic - the mnemonic to use for the action. Should be a single character.

   smicon - the relative path to an image in the classpath that represents
            a small icon.

   icon - the relative path to an image in the classpath that represents an icon.

   desc - a short description of the action.

    
   accel - a string that represents the keyboard accelerator to invoke
           the action. The string should be formatted according to the syntax
           outlined in the javadoc for the static method:

                     javax.swing.KeyStroke#getKeyStroke(String)

           For example, the string "control S" represents the Control-S key.
-->

<!ENTITY % action_attributes "idref     IDREF #IMPLIED
          type      (single | toggle) #IMPLIED
          name      CDATA #IMPLIED
          mnemonic  CDATA #IMPLIED
          smicon    CDATA #IMPLIED
          icon      CDATA #IMPLIED
          desc      CDATA #IMPLIED
          accel     CDATA #IMPLIED"
>

<!-- 
    An action-set is a set of user action properties and the arangement
    of these user actions into lists and trees (which are lists of lists).

    action-sets may be reused between applications by including them as 
    parsed external entities - which acts as text substitution. 
    An action-set which is used as an external entity cannot have an XML 
    declaration or a document type definition. 
-->

<!ELEMENT action-set (action | action-list | action-set)*>
<!ATTLIST action-set
          id        ID #REQUIRED
>

<!-- 
    The action element represents the properties of a javax.swing.Action. 
    This element can be a placeholder for an action within an action-list.
    
    id - a unique id for the action.

    The idref attribute should be used instead of the id attribute if an action 
    refers to a previous action definition. An action with both an id and 
    idref is undefined.

    See the desciption for the action_attributes entity for a detailed
    description of the rest of the attributes.

-->

<!ELEMENT action EMPTY>
<!ATTLIST action 
          id        ID #IMPLIED
          %action_attributes;
>


<!--
    The action-list is used to define lists and trees of actions.
    These can map to toolbars, menus and popups.

    See the desciption for the action_attributes entity for a detailed
    description of the rest of the attributes.
-->

<!ELEMENT action-list (action | empty | action-list | group)*>
<!ATTLIST action-list
          id        ID #REQUIRED
          %action_attributes;
>

<!--
    The group element indicates a grouping of toggle actions. A parser
    implementation can use this information to add components to a button
    group so that the selection between components will be mutaully
    exclusive.

    All the action elements in a group element will belong to the 
    same button group. The action elements in a group should have
    the type="toggle" attribute
-->

<!ELEMENT group (action)*>
<!ATTLIST group
          id        CDATA #REQUIRED
>

<!--
    The empty element acts as padding around an actionlist structure.
    This may be intepreted as a separator.
-->

<!ELEMENT empty EMPTY>

=== Garnasha/quantomatic/gui/src/quanto/gui/resources/actions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE action-set SYSTEM "action-set.dtd">

<!--
  The actions define all the Actions in an application
  and toolbars and menus which use the actions

  Every action needs a corresponding registration somewhere
  in the code that specifies what to do when the action is
  triggered.  For "global" actions (such as new graph, open,
  quit), this is in QuantoFrame (the CommandAction and
  BoolPrefAction enums).  For actions that are delegated to
  views (the document-centric ones such as save, cut, select
  all etc.), there should be an entry in CommandManager that
  fixes the string name of the action (so typos can only be
  in one place), and code to deal with/enable/disable those
  actions should be in the relevant views.
-->

<action-set id="quanto-frame">


	<!-- File menu operations -->

	<action id="new-win-command"
          name="New window"
          mnemonic="W"
          accel="control shift N"
          desc="Open a new window"/>

	<action id="new-graph-command"
          name="New graph"
          mnemonic="N"
          smicon="/toolbarButtonGraphics/general/New16.gif"
          icon="/toolbarButtonGraphics/general/New24.gif"
	  accel="control N"
          desc="Create a new graph"/>

	<action id="open-command"
          name="Open graph..."
          mnemonic="O"
          smicon="/toolbarButtonGraphics/general/Open16.gif"
          icon="/toolbarButtonGraphics/general/Open24.gif"
          accel="control O"
          desc="Open an existing graph"/>

	<action id="save-command"
          name="Save"
          mnemonic="S"
          smicon="/toolbarButtonGraphics/general/Save16.gif"
          icon="/toolbarButtonGraphics/general/Save24.gif"
	  accel="control S"
          desc="Save the current graph"/>

	<action id="save-as-command"
          name="Save as..."
          mnemonic="a"
          accel="control shift S"
          smicon="/toolbarButtonGraphics/general/SaveAs16.gif"
          icon="/toolbarButtonGraphics/general/SaveAs24.gif"
          desc="Save the current graph under a different name"/>

	<action id="load-theory-command"
		name="Load theory..."
		mnemonic="T"
		desc="Load a theory file" />

	<action id="load-ruleset-command"
          name="Import ruleset..."
          mnemonic="i"
          desc="Load a ruleset"/>

	<action id="save-ruleset-command"
          name="Export ruleset..."
          mnemonic="e"
          desc="Save the loaded rule state"/>

	<action id="close-command"
          name="Close"
          mnemonic="c"
	  accel="control W"
          desc="Close the current graph or view"/>

	<action id="quit-command"
          name="Quit"
          mnemonic="q"
	  accel="control Q"
          desc="Quits the application"/>

	<!-- Edit menu commands -->

	<action id="undo-command"
          name="Undo"
          mnemonic="U"
          smicon="/toolbarButtonGraphics/general/Undo16.gif"
          icon="/toolbarButtonGraphics/general/Undo24.gif"
	  accel="control Z"
          desc="Undo the last action"/>

	<action id="redo-command"
          name="Redo"
          mnemonic="r"
          smicon="/toolbarButtonGraphics/general/Redo16.gif"
          icon="/toolbarButtonGraphics/general/Redo24.gif"
	  accel="control Y"
          desc="Redo the action that was last undone"/>

	<action id="undo-rewrite-command"
          name="Undo Rewrite"
          mnemonic="U"
	  accel="control shift Z"
          desc="Undo the last rewrite"/>

	<action id="redo-rewrite-command"
          name="Redo Rewrite"
          mnemonic="r"
	  accel="control shift Y"
          desc="Redo the rewrite that was last undone"/>

	<action id="copy-command"
          name="Copy"
          mnemonic="C"
          smicon="/toolbarButtonGraphics/general/Copy16.gif"
          icon="/toolbarButtonGraphics/general/Copy24.gif"
	  accel="control C"
          desc="Copy the selected item to the clipboard"/>

	<action id="cut-command"
          name="Cut"
          mnemonic="T"
          smicon="/toolbarButtonGraphics/general/Cut16.gif"
          icon="/toolbarButtonGraphics/general/Cut24.gif"
	  accel="control X"
          desc="Remove selected item and place it on the clipboard"/>

	<action id="paste-command"
          name="Paste"
          mnemonic="P"
          smicon="/toolbarButtonGraphics/general/Paste16.gif"
          icon="/toolbarButtonGraphics/general/Paste24.gif"
	  accel="control V"
          desc="Inserts an object from the clipboard"/>

	<action id="select-all-command"
          name="Select all"
          mnemonic="S"
	  accel="control A"
          desc="Select all visible items"/>

	<action id="deselect-all-command"
          name="Deselect all"
          mnemonic="D"
	  accel="control shift A"
          desc="Unselect all selected items"/>

	<action id="abort-command"
          name="Abort all"
          mnemonic="A"
	  accel="control PERIOD"
          desc="Abort all operations running on the current document"/>

	<!-- View menu commands -->

	<action id="refresh-graph-command"
          name="Refresh graph"
          mnemonic="R"
          desc="Reload graph from core"/>

	<action id="relayout-graph-command"
          name="Re-layout graph"
          mnemonic="L"
          desc="Refresh the current graphs"/>

	<action id="internal-graph-names-command"
	  type="toggle"
	  name="Show internal graph names"
	  mnemonic="S"
	  desc="Show the graph names used internally by the backend in the window list"/>

	<action id="open-in-new-window-command"
	  type="toggle"
	  name="Open graphs in new window"
	  mnemonic="O"
	  desc="Use a new window when opening or creating graphs"/>

	<!-- Graph menu commands -->

	<action id="export-to-pdf-command"
          name="Export to PDF"
          mnemonic="P"
          desc="Export the graph as a PDF file"/>

	<action id="select-mode-command"
	  type="toggle"
          name="Select mode"
          mnemonic="S"
	  accel="control shift S"
          smicon="/toolbarButtonGraphics/general/Select16.gif"
          icon="/toolbarButtonGraphics/general/Select24.gif"
          desc="Select, move and edit graph items"/>

	<action id="directed-edge-mode-command"
	  type="toggle"
          name="Directed Edge mode"
          mnemonic="D"
	  accel="control shift D"
          smicon="/toolbarButtonGraphics/quanto/DirectedLink16.gif"
          icon="/toolbarButtonGraphics/quanto/DirectedLink24.gif"
          desc="Add directed edges to the graph"/>

	<action id="undirected-edge-mode-command"
	  type="toggle"
          name="Undirected Edge mode"
          mnemonic="E"
	  accel="control shift E"
          smicon="/toolbarButtonGraphics/quanto/Link16.gif"
          icon="/toolbarButtonGraphics/quanto/Link24.gif"
          desc="Add undirected edges to the graph"/>

	<action id="latex-to-clipboard-command"
          name="Latex to clipboard"
          mnemonic="T"
          desc="Export the graph as a Latex document, placing it on the clipboard"/>

	<action id="show-rewrites-command"
          name="Show rewrites"
          mnemonic="R"
	  accel="control SPACE"
          desc="Show all the available rewrites that can be performed on the graph"/>

	<action id="normalise-command"
          name="Normalise"
          mnemonic="N"
	  accel="control G"
          desc="Normalise the graph, showing each step"/>

	<action id="fast-normalise-command"
          name="Fast normalise"
          mnemonic="F"
	  accel="control shift G"
          desc="Normalise the graph without showing individual steps"/>

	<action id="lock-vertices-command"
          name="Lock vertices"
          mnemonic="L"
	  accel="control L"
          desc="Lock the selected vertices"/>

	<action id="unlock-vertices-command"
          name="Unlock vertices"
          mnemonic="U"
	  accel="control shift L"
          desc="Unlock the selected vertices"/>

	<!-- Bang box menu commands -->

	<action id="bang-vertices-command"
          name="Bang vertices"
          mnemonic="B"
	  accel="control 1"
          desc="Create a bang box containing the selected vertices"/>

	<action id="unbang-vertices-command"
          name="Unbang vertices"
          mnemonic="U"
	  accel="control shift 1"
          desc="Remove the selected vertices from their bang boxes"/>

	<action id="drop-bang-box-command"
          name="Drop bang box"
          mnemonic="D"
	  accel="shift backspace"
          desc="Remove the selected bang box, leaving the contained nodes alone"/>

	<action id="kill-bang-box-command"
          name="Kill bang box"
          mnemonic="K"
	  accel="control shift backspace"
          desc="Remove the selected bang box and all the nodes it contains"/>

	<action id="duplicate-bang-box-command"
          name="Duplicate bang box"
          mnemonic="P"
	  accel="control D"
          desc="Duplicate the selected bang box"/>

	<!-- Hilbert space menu commands -->

	<action id="hilbert-as-text-command"
          name="Hilbert space term as text"
          mnemonic="t"
          desc="Get the Hilbert space term for the graph in text format"/>

	<action id="hilbert-as-mathematica-command"
          name="Hilbert space term as Mathematica"
          mnemonic="M"
          desc="Get the Hilbert space term for the graph in Mathematica format"/>

	<!-- Rule menu commands -->

	<!--action id="use-rule-command"
          name="Use rule"
          mnemonic="U"
          desc="Use the current rule"/-->

	<!-- Help menu commands -->

	<action id="about-command"
          name="About..."
          mnemonic="A"
          smicon="/toolbarButtonGraphics/general/About16.gif"
          icon="/toolbarButtonGraphics/general/About24.gif"
          desc="Information about the application"/>

	<!-- Define the main menu -->


	<action-list id="main-menu">
		<action-list id="file-menu" name="File" mnemonic="F">
			<action idref="new-win-command"/>
			<action idref="new-graph-command"/>
			<action idref="open-command" />
			<action idref="save-command"/>
			<action idref="save-as-command"/>
			<empty/>
